title: ApathyM's Customized Title
author: ApathyM
email: matthewadrian97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Explore this experience of a brand new programming user at its very early stages of debelopment.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ApathyM

show_excerpts: true # set to false to remove excerpts on the homepage
